### PR TITLE
added test to package_data

### PR DESCRIPTION
**Pull request by AmanuelAaron**
I am trying to add a test in Circle CI that runs bouncerscript against Nazgul. I need this change to include the test JSON files

### CODE REVIEW

**Comment by AmanuelAaron** [comment]
@MihaiTabara

**Comment by AmanuelAaron** [comment]
I have CircleCI running on the [Nazgul repo](https://github.com/mozilla-services/bouncer-admin/tree/bouncerscript-test). As part of our tests, we run bouncerscript against Nazgul. It looks like this:
```
sudo pip3 install https://github.com/AmanuelAaron/bouncerscript/archive/server-integration-test.zip
python3 main.py &
bouncerscript bouncerscript_config.json
```
Eventually we want to change the pip install to mozilla-releng/bouncerscript instead of my fork. The config for the bouncerscript test can be found [here](https://github.com/mozilla-services/bouncer-admin/blob/bouncerscript-test/bouncerscript_config.json).

**Comment by MihaiTabara** [comment]
@AmanuelAaron Sorry for delays in getting back to this PR, it slipped my radar. So there's two things here:

1. If this unblocks you, I'm happy to merge. However, I don't see how this will help as `test_work_dir` doesn't come with the package itself, unless made via `mkdir`. I assume you've already configured your local bouncerscript run to encompass those folders? 

2. Another possibility would be to maybe clone this repo, create the virtualenv and run it from the local installation? There's docs to describe this for another project of ours (beetmoverscript, similar in setup with bouncerscript) [here](https://github.com/mozilla-releng/beetmoverscript/#setup-py3-venv) and [here](https://github.com/mozilla-releng/beetmoverscript/#with-scriptworker-via-task-creator-in-taskcluster-tools).

Happy to meet over Zoom or talk more over Slack to make sure I unblock you here 👍

**Comment by MihaiTabara** [comment]
Closing this as @AmanuelAaron and myself met over Zoom to solve this last week. Feel free to re-open should this is needed again.

**Pull request closed without merging**
